apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"name":"ingress-nginx","namespace":"observability"},"spec":{"endpoints":[{"interval":"30s","path":"/metrics","port":"metrics","scheme":"http"}],"namespaceSelector":{"matchNames":["ingress-nginx"]},"selector":{"matchLabels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"ingress-nginx"}}}}
    creationTimestamp: "2025-11-05T14:32:14Z"
    generation: 1
    labels:
      release: monitor
    name: ingress-nginx
    namespace: observability
    resourceVersion: "103916"
    uid: eb3440a2-c490-4f93-8498-5157346eda9c
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - ingress-nginx
    selector:
      matchLabels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: ingress-nginx
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.2.1
      helm.sh/chart: grafana-10.1.4
    name: monitor-grafana
    namespace: observability
    resourceVersion: "57218"
    uid: 3fbbcb2c-d34a-469e-8cd7-e39feb5e82b5
  spec:
    endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      scheme: http
      scrapeTimeout: 30s
    jobLabel: monitor
    namespaceSelector:
      matchNames:
      - observability
    selector:
      matchLabels:
        app.kubernetes.io/instance: monitor
        app.kubernetes.io/name: grafana
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-alertmanager
    namespace: observability
    resourceVersion: "57214"
    uid: d9c2e27d-5c38-479f-b97b-e00ad49c87eb
  spec:
    endpoints:
    - enableHttp2: true
      path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
    namespaceSelector:
      matchNames:
      - observability
    selector:
      matchLabels:
        app: kube-prometheus-stack-alertmanager
        release: monitor
        self-monitor: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-apiserver
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-apiserver
    namespace: observability
    resourceVersion: "57220"
    uid: d48fd463-b175-4b8d-8b8f-28fbbe4b5db5
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      metricRelabelings:
      - action: drop
        regex: (etcd_request|apiserver_request_slo|apiserver_request_sli|apiserver_request)_duration_seconds_bucket;(0\.15|0\.2|0\.3|0\.35|0\.4|0\.45|0\.6|0\.7|0\.8|0\.9|1\.25|1\.5|1\.75|2|3|3\.5|4|4\.5|6|7|8|9|15|20|40|45|50)(\.0)?
        sourceLabels:
        - __name__
        - le
      port: https
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: false
        serverName: kubernetes
    jobLabel: component
    namespaceSelector:
      matchNames:
      - default
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-coredns
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-coredns
    namespace: observability
    resourceVersion: "57211"
    uid: 9becd924-5082-4ade-8a19-b45802fe82ef
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-coredns
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kube-controller-manager
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-kube-controller-manager
    namespace: observability
    resourceVersion: "57213"
    uid: e5d8eabc-2686-47b3-94aa-42ff64b3586e
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-kube-controller-manager
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kube-etcd
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-kube-etcd
    namespace: observability
    resourceVersion: "57209"
    uid: f83046f5-796f-45e4-bb6e-1c61deda20e1
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-kube-etcd
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kube-proxy
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-kube-proxy
    namespace: observability
    resourceVersion: "57219"
    uid: dd26d700-d5f2-4ba5-ac28-a2bfeb10dc46
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-kube-proxy
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kube-scheduler
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-kube-scheduler
    namespace: observability
    resourceVersion: "57208"
    uid: 2e561508-bcac-4260-ae88-0a3607785dbb
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: jobLabel
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app: kube-prometheus-stack-kube-scheduler
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-kubelet
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-kubelet
    namespace: observability
    resourceVersion: "57216"
    uid: 6dce7bbe-6ba7-4e71-8621-0a525d135664
  spec:
    attachMetadata:
      node: false
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      metricRelabelings:
      - action: drop
        regex: (csi_operations|storage_operation_duration)_seconds_bucket;(0.25|2.5|15|25|120|600)(\.0)?
        sourceLabels:
        - __name__
        - le
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      interval: 10s
      metricRelabelings:
      - action: drop
        regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_memory_(mapped_file|swap)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_(file_descriptors|tasks_state|threads_max)
        sourceLabels:
        - __name__
      - action: drop
        regex: container_memory_failures_total;hierarchy
        sourceLabels:
        - __name__
        - scope
      - action: drop
        regex: container_network_.*;(cali|cilium|cni|lxc|nodelocaldns|tunl).*
        sourceLabels:
        - __name__
        - interface
      - action: drop
        regex: container_spec.*
        sourceLabels:
        - __name__
      - action: drop
        regex: .+;
        sourceLabels:
        - id
        - pod
      path: /metrics/cadvisor
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
      trackTimestampsStaleness: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      honorTimestamps: true
      path: /metrics/probes
      port: https-metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __metrics_path__
        targetLabel: metrics_path
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
    jobLabel: k8s-app
    namespaceSelector:
      matchNames:
      - kube-system
    selector:
      matchLabels:
        app.kubernetes.io/name: kubelet
        k8s-app: kubelet
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-operator
      app.kubernetes.io/component: prometheus-operator
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-operator
    namespace: observability
    resourceVersion: "57215"
    uid: 0ce292e2-765b-4ae6-aaa3-1a9d4143b7f2
  spec:
    endpoints:
    - honorLabels: true
      port: https
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: ca
            name: monitor-kube-prometheus-st-admission
            optional: false
        serverName: monitor-kube-prometheus-st-operator
    namespaceSelector:
      matchNames:
      - observability
    selector:
      matchLabels:
        app: kube-prometheus-stack-operator
        release: monitor
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 79.1.1
      chart: kube-prometheus-stack-79.1.1
      heritage: Helm
      release: monitor
    name: monitor-kube-prometheus-st-prometheus
    namespace: observability
    resourceVersion: "57212"
    uid: 8cf3432d-1b18-4514-bd0e-f39e099e89fd
  spec:
    endpoints:
    - path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
    namespaceSelector:
      matchNames:
      - observability
    selector:
      matchLabels:
        app: kube-prometheus-stack-prometheus
        release: monitor
        self-monitor: "true"
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.17.0
      helm.sh/chart: kube-state-metrics-6.3.0
      release: monitor
    name: monitor-kube-state-metrics
    namespace: observability
    resourceVersion: "57210"
    uid: 1237d333-c256-4c90-a565-eefb9da9af7d
  spec:
    endpoints:
    - honorLabels: true
      port: http
    jobLabel: app.kubernetes.io/name
    selector:
      matchLabels:
        app.kubernetes.io/instance: monitor
        app.kubernetes.io/name: kube-state-metrics
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: monitor
      meta.helm.sh/release-namespace: observability
    creationTimestamp: "2025-11-05T08:32:08Z"
    generation: 1
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.10.2
      helm.sh/chart: prometheus-node-exporter-4.49.1
      release: monitor
    name: monitor-prometheus-node-exporter
    namespace: observability
    resourceVersion: "57217"
    uid: 5a030bde-2590-4720-a959-f8b55dd6489d
  spec:
    attachMetadata:
      node: false
    endpoints:
    - port: http-metrics
      scheme: http
    jobLabel: jobLabel
    selector:
      matchLabels:
        app.kubernetes.io/instance: monitor
        app.kubernetes.io/name: prometheus-node-exporter
kind: List
metadata:
  resourceVersion: ""
